exports.countryList = [
  { code: "AF", name: "Afghanistan", status: true },
  { code: "AL", name: "Albania", status: true },
  { code: "DZ", name: "Algeria", status: true },
  { code: "AS", name: "American Samoa", status: true },
  { code: "AD", name: "Andorra", status: true },
  { code: "AO", name: "Angola", status: true },
  { code: "AI", name: "Anguilla", status: true },
  { code: "AQ", name: "Antarctica", status: true },
  { code: "AG", name: "Antigua and Barbuda", status: true },
  { code: "AR", name: "Argentina", status: true },
  { code: "AM", name: "Armenia", status: true },
  { code: "AW", name: "Aruba", status: true },
  { code: "AU", name: "Australia", status: true },
  { code: "AT", name: "Austria", status: true },
  { code: "AZ", name: "Azerbaijan", status: true },
  { code: "BS", name: "Bahamas (the)", status: true },
  { code: "BH", name: "Bahrain", status: true },
  { code: "BD", name: "Bangladesh", status: true },
  { code: "BB", name: "Barbados", status: true },
  { code: "BY", name: "Belarus", status: true },
  { code: "BE", name: "Belgium", status: true },
  { code: "BZ", name: "Belize", status: true },
  { code: "BJ", name: "Benin", status: true },
  { code: "BM", name: "Bermuda", status: true },
  { code: "BT", name: "Bhutan", status: true },
  {
    code: "BO",
    name: "Bolivia (Plurinational State of)",
    status: true,
  },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    status: true,
  },
  { code: "BA", name: "Bosnia and Herzegovina", status: true },
  { code: "BW", name: "Botswana", status: true },
  { code: "BV", name: "Bouvet Island", status: true },
  { code: "BR", name: "Brazil", status: true },
  {
    code: "IO",
    name: "British Indian Ocean Territory (the)",
    status: true,
  },
  { code: "BN", name: "Brunei Darussalam", status: true },
  { code: "BG", name: "Bulgaria", status: true },
  { code: "BF", name: "Burkina Faso", status: true },
  { code: "BI", name: "Burundi", status: true },
  { code: "CV", name: "Cabo Verde", status: true },
  { code: "KH", name: "Cambodia", status: true },
  { code: "CM", name: "Cameroon", status: true },
  { code: "CA", name: "Canada", status: true },
  { code: "KY", name: "Cayman Islands (the)", status: true },
  {
    code: "CF",
    name: "Central African Republic (the)",
    status: true,
  },
  { code: "TD", name: "Chad", status: true },
  { code: "CL", name: "Chile", status: true },
  { code: "CN", name: "China", status: true },
  { code: "CX", name: "Christmas Island", status: true },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands (the)",
    status: true,
  },
  { code: "CO", name: "Colombia", status: true },
  { code: "KM", name: "Comoros (the)", status: true },
  {
    code: "CD",
    name: "Congo (the Democratic Republic of the)",
    status: true,
  },
  { code: "CG", name: "Congo (the)", status: true },
  { code: "CK", name: "Cook Islands (the)", status: true },
  { code: "CR", name: "Costa Rica", status: true },
  { code: "HR", name: "Croatia", status: true },
  { code: "CU", name: "Cuba", status: true },
  { code: "CW", name: "Curaçao", status: true },
  { code: "CY", name: "Cyprus", status: true },
  { code: "CZ", name: "Czechia", status: true },
  // { code: "CI", name: "Côte dIvoire", status: true },
  { code: "DK", name: "Denmark", status: true },
  { code: "DJ", name: "Djibouti", status: true },
  { code: "DM", name: "Dominica", status: true },
  { code: "DO", name: "Dominican Republic (the)", status: true },
  { code: "EC", name: "Ecuador", status: true },
  { code: "EG", name: "Egypt", status: true },
  { code: "SV", name: "El Salvador", status: true },
  { code: "GQ", name: "Equatorial Guinea", status: true },
  { code: "ER", name: "Eritrea", status: true },
  { code: "EE", name: "Estonia", status: true },
  { code: "SZ", name: "Eswatini", status: true },
  { code: "ET", name: "Ethiopia", status: true },
  {
    code: "FK",
    name: "Falkland Islands (the) [Malvinas]",
    status: true,
  },
  { code: "FO", name: "Faroe Islands (the)", status: true },
  { code: "FJ", name: "Fiji", status: true },
  { code: "FI", name: "Finland", status: true },
  { code: "FR", name: "France", status: true },
  { code: "GF", name: "French Guiana", status: true },
  { code: "PF", name: "French Polynesia", status: true },
  {
    code: "TF",
    name: "French Southern Territories (the)",
    status: true,
  },
  { code: "GA", name: "Gabon", status: true },
  { code: "GM", name: "Gambia (the)", status: true },
  { code: "GE", name: "Georgia", status: true },
  { code: "DE", name: "Germany", status: true },
  { code: "GH", name: "Ghana", status: true },
  { code: "GI", name: "Gibraltar", status: true },
  { code: "GR", name: "Greece", status: true },
  { code: "GL", name: "Greenland", status: true },
  { code: "GD", name: "Grenada", status: true },
  { code: "GP", name: "Guadeloupe", status: true },
  { code: "GU", name: "Guam", status: true },
  { code: "GT", name: "Guatemala", status: true },
  { code: "GG", name: "Guernsey", status: true },
  { code: "GN", name: "Guinea", status: true },
  { code: "GW", name: "Guinea-Bissau", status: true },
  { code: "GY", name: "Guyana", status: true },
  { code: "HT", name: "Haiti", status: true },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    status: true,
  },
  { code: "VA", name: "Holy See (the)", status: true },
  { code: "HN", name: "Honduras", status: true },
  { code: "HK", name: "Hong Kong", status: true },
  { code: "HU", name: "Hungary", status: true },
  { code: "IS", name: "Iceland", status: true },
  { code: "IN", name: "India", status: true },
  { code: "ID", name: "Indonesia", status: true },
  { code: "IR", name: "Iran (Islamic Republic of)", status: true },
  { code: "IQ", name: "Iraq", status: true },
  { code: "IE", name: "Ireland", status: true },
  { code: "IM", name: "Isle of Man", status: true },
  { code: "IL", name: "Israel", status: true },
  { code: "IT", name: "Italy", status: true },
  { code: "JM", name: "Jamaica", status: true },
  { code: "JP", name: "Japan", status: true },
  { code: "JE", name: "Jersey", status: true },
  { code: "JO", name: "Jordan", status: true },
  { code: "KZ", name: "Kazakhstan", status: true },
  { code: "KE", name: "Kenya", status: true },
  { code: "KI", name: "Kiribati", status: true },
  {
    code: "KP",
    name: "Korea (the Democratic Peoples Republic of)",
    status: true,
  },
  { code: "KR", name: "Korea (the Republic of)", status: true },
  { code: "KW", name: "Kuwait", status: true },
  { code: "KG", name: "Kyrgyzstan", status: true },
  {
    code: "LA",
    name: "Lao Peoples Democratic Republic (the)",
    status: true,
  },
  { code: "LV", name: "Latvia", status: true },
  { code: "LB", name: "Lebanon", status: true },
  { code: "LS", name: "Lesotho", status: true },
  { code: "LR", name: "Liberia", status: true },
  { code: "LY", name: "Libya", status: true },
  { code: "LI", name: "Liechtenstein", status: true },
  { code: "LT", name: "Lithuania", status: true },
  { code: "LU", name: "Luxembourg", status: true },
  { code: "MO", name: "Macao", status: true },
  { code: "MG", name: "Madagascar", status: true },
  { code: "MW", name: "Malawi", status: true },
  { code: "MY", name: "Malaysia", status: true },
  { code: "MV", name: "Maldives", status: true },
  { code: "ML", name: "Mali", status: true },
  { code: "MT", name: "Malta", status: true },
  { code: "MH", name: "Marshall Islands (the)", status: true },
  { code: "MQ", name: "Martinique", status: true },
  { code: "MR", name: "Mauritania", status: true },
  { code: "MU", name: "Mauritius", status: true },
  { code: "YT", name: "Mayotte", status: true },
  { code: "MX", name: "Mexico", status: true },
  {
    code: "FM",
    name: "Micronesia (Federated States of)",
    status: true,
  },
  { code: "MD", name: "Moldova (the Republic of)", status: true },
  { code: "MC", name: "Monaco", status: true },
  { code: "MN", name: "Mongolia", status: true },
  { code: "ME", name: "Montenegro", status: true },
  { code: "MS", name: "Montserrat", status: true },
  { code: "MA", name: "Morocco", status: true },
  { code: "MZ", name: "Mozambique", status: true },
  { code: "MM", name: "Myanmar", status: true },
  { code: "NA", name: "Namibia", status: true },
  { code: "NR", name: "Nauru", status: true },
  { code: "NP", name: "Nepal", status: true },
  { code: "NL", name: "Netherlands (the)", status: true },
  { code: "NC", name: "New Caledonia", status: true },
  { code: "NZ", name: "New Zealand", status: true },
  { code: "NI", name: "Nicaragua", status: true },
  { code: "NE", name: "Niger (the)", status: true },
  { code: "NG", name: "Nigeria", status: true },
  { code: "NU", name: "Niue", status: true },
  { code: "NF", name: "Norfolk Island", status: true },
  {
    code: "MP",
    name: "Northern Mariana Islands (the)",
    status: true,
  },
  { code: "NO", name: "Norway", status: true },
  { code: "OM", name: "Oman", status: true },
  { code: "PK", name: "Pakistan", status: true },
  { code: "PW", name: "Palau", status: true },
  { code: "PS", name: "Palestine, State of", status: true },
  { code: "PA", name: "Panama", status: true },
  { code: "PG", name: "Papua New Guinea", status: true },
  { code: "PY", name: "Paraguay", status: true },
  { code: "PE", name: "Peru", status: true },
  { code: "PH", name: "Philippines (the)", status: true },
  { code: "PN", name: "Pitcairn", status: true },
  { code: "PL", name: "Poland", status: true },
  { code: "PT", name: "Portugal", status: true },
  { code: "PR", name: "Puerto Rico", status: true },
  { code: "QA", name: "Qatar", status: true },
  { code: "MK", name: "Republic of North Macedonia", status: true },
  { code: "RO", name: "Romania", status: true },
  { code: "RU", name: "Russian Federation (the)", status: true },
  { code: "RW", name: "Rwanda", status: true },
  { code: "RE", name: "Réunion", status: true },
  { code: "BL", name: "Saint Barthélemy", status: true },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    status: true,
  },
  { code: "KN", name: "Saint Kitts and Nevis", status: true },
  { code: "LC", name: "Saint Lucia", status: true },
  { code: "MF", name: "Saint Martin (French part)", status: true },
  { code: "PM", name: "Saint Pierre and Miquelon", status: true },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    status: true,
  },
  { code: "WS", name: "Samoa", status: true },
  { code: "SM", name: "San Marino", status: true },
  { code: "ST", name: "Sao Tome and Principe", status: true },
  { code: "SA", name: "Saudi Arabia", status: true },
  { code: "SN", name: "Senegal", status: true },
  { code: "RS", name: "Serbia", status: true },
  { code: "SC", name: "Seychelles", status: true },
  { code: "SL", name: "Sierra Leone", status: true },
  { code: "SG", name: "Singapore", status: true },
  { code: "SX", name: "Sint Maarten (Dutch part)", status: true },
  { code: "SK", name: "Slovakia", status: true },
  { code: "SI", name: "Slovenia", status: true },
  { code: "SB", name: "Solomon Islands", status: true },
  { code: "SO", name: "Somalia", status: true },
  { code: "ZA", name: "South Africa", status: true },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    status: true,
  },
  { code: "SS", name: "South Sudan", status: true },
  { code: "ES", name: "Spain", status: true },
  { code: "LK", name: "Sri Lanka", status: true },
  { code: "SD", name: "Sudan (the)", status: true },
  { code: "SR", name: "Suriname", status: true },
  { code: "SJ", name: "Svalbard and Jan Mayen", status: true },
  { code: "SE", name: "Sweden", status: true },
  { code: "CH", name: "Switzerland", status: true },
  { code: "SY", name: "Syrian Arab Republic", status: true },
  { code: "TW", name: "Taiwan", status: true },
  { code: "TJ", name: "Tajikistan", status: true },
  { code: "TZ", name: "Tanzania, United Republic of", status: true },
  { code: "TH", name: "Thailand", status: true },
  { code: "TL", name: "Timor-Leste", status: true },
  { code: "TG", name: "Togo", status: true },
  { code: "TK", name: "Tokelau", status: true },
  { code: "TO", name: "Tonga", status: true },
  { code: "TT", name: "Trinidad and Tobago", status: true },
  { code: "TN", name: "Tunisia", status: true },
  { code: "TR", name: "Turkey", status: true },
  { code: "TM", name: "Turkmenistan", status: true },
  {
    code: "TC",
    name: "Turks and Caicos Islands (the)",
    status: true,
  },
  { code: "TV", name: "Tuvalu", status: true },
  { code: "UG", name: "Uganda", status: true },
  { code: "UA", name: "Ukraine", status: true },
  { code: "AE", name: "United Arab Emirates (the)", status: true },
  {
    code: "GB",
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    status: true,
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands (the)",
    status: true,
  },
  {
    code: "US",
    name: "United States of America (the)",
    status: true,
  },
  { code: "UY", name: "Uruguay", status: true },
  { code: "UZ", name: "Uzbekistan", status: true },
  { code: "VU", name: "Vanuatu", status: true },
  {
    code: "VE",
    name: "Venezuela (Bolivarian Republic of)",
    status: true,
  },
  { code: "VN", name: "Viet Nam", status: true },
  { code: "VG", name: "Virgin Islands (British)", status: true },
  { code: "VI", name: "Virgin Islands (U.S.)", status: true },
  { code: "WF", name: "Wallis and Futuna", status: true },
  { code: "EH", name: "Western Sahara", status: true },
  { code: "YE", name: "Yemen", status: true },
  { code: "ZM", name: "Zambia", status: true },
  { code: "ZW", name: "Zimbabwe", status: true },
  { code: "AX", name: "Åland Islands", status: true },
];
